### ISSUE TITLE
Open Context Plugin Sdk is not working.

### ISSUE THREAD

**Issue by raiuli** [OrganicityEu/android-experimentation-experiments#1]
I have downloaded the projects from
    https://github.com/OrganicityEu/smartphone-experimentation-experiments.git
    https://github.com/OrganicityEu/smartphone-experimentation-plugins.git

My problem is with the Open_Context_Plugin_Sdk. When I am trying to build
the mobile application named “WifiScanPlugin”, i am getting following
error for the MANIFEST.MF file of Open_Context_Plugin_Sdk.

Package ‘org.ambientdynamix.api.application' does not exist in this
plug-in MANIFEST.MF /Open
Context Plugin Sdk/META-INF line 7

Although the library file org.ambientdynamix.contextplugin.api_v0.9.54.jar
is in the lib folder and the jar file contains the package above-metioned.

**Comment by amaxilat** [comment]
Hi @raiuli ,

Did you follow the guide for installing the Ambient Dynamix framework presented [here](http://ambientdynamix.org/documentation/plug-in-development-guide) ?

After installing the SDK  you do not need to build the app, you just need to go to `Export` -> `Deployable Plugins and Fragments` and select from the list only the plugin you need to build.
